language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - COVERALLS=1

before_script:
  - printf "\n" | pecl install imagick
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install --prefer-dist --no-interaction
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

script:
  - vendor/bin/phpunit
  - sh -c "if [ '$COVERALLS' = '1' ]; then vendor/bin/phpunit --stderr --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
